// Referencias globales para el proyecto
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using Microsoft.EntityFrameworkCore;
global using ClubManager.Commands;
global using ClubManager.Data;
global using ClubManager.Models;
global using ClubManager.Services;
global using ClubManager.Views;
global using MessageBox = System.Windows.MessageBox;
global using UserControl = System.Windows.Controls.UserControl;
global using Application = System.Windows.Application;
global using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
global using Clipboard = System.Windows.Clipboard;
global using Color = System.Windows.Media.Color;
global using ColorConverter = System.Windows.Media.ColorConverter;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using UserSession = ClubManager.Models.UserSession;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
global using MouseEventArgs = System.Windows.Input.MouseEventArgs;
global using FontStyle = System.Windows.FontStyle;
global using Image = System.Windows.Controls.Image;
global using Brushes = System.Windows.Media.Brushes;
global using Point = System.Windows.Point;
global using Rectangle = System.Windows.Shapes.Rectangle;
global using TextBox = System.Windows.Controls.TextBox;
global using FontFamily = System.Windows.Media.FontFamily;
global using Cursors = System.Windows.Input.Cursors;
global using Brush = System.Windows.Media.Brush;
global using ThemeMode = ClubManager.Services.ThemeMode;
